### ISSUE TITLE
Problema com testadores.

### ISSUE THREAD

**Issue by MfixCode** [DroidScript/Docs#234]
Estou tendo problemas com a falta de engajamento das pessoas em testar os aplicativos. Tem algum grupo que testa? Se alguém puder ajudar.

**Comment by Al4He6** [comment]
Translates as 
I'm having problems with the lack of engagement of people in testing the apps. Is there any group that tests? If anyone can help.
This forum is for problems in the documentation.
Your request should be entered on Google Groups, or Discord.
