### ISSUE TITLE
Erro Android 14

### ISSUE THREAD

**Issue by MfixCode** [DroidScript/Docs#236]
Em alguns aparelhos com Android 14 está gerando erro anr demora pra abrir, não está respondendo. Fica com mensagem fechar aplicativo ou aguardar

java.lang.SecurityException: com.myname.fastlist: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by Al4He6** [comment]
Translates as
On some devices with Android 14 it is generating error anr takes time to open, it is not responding. Keeps with message close app or wait
Again this should be asked in the Google Groups or discord
