### ISSUE TITLE
app.Uri2Path needs deprecating

### ISSUE THREAD

**Issue by dhurren** [DroidScript/Docs#50]
In recent versions of Android, its no longer to query the content database for the _data column (for security reasons) which makes it impossible to work out the original file path.  So we need to mark app.Uri2Path as deprecated in the docs and make sure all DS methods can cope with URI as well as absolute path.

**Comment by alex-Symbroson** [comment]
fixed by 32b649cc3a0b9e9ef6d0ec89da948890a5f13376
