### ISSUE TITLE
app.GetInstalledApps() and app.GetAcitivites() need a warning notice and/or deprecation

### ISSUE THREAD

**Issue by Right2TheV0id** [DroidScript/Docs#51]
Testing the **Launcher** sample I noticed **app.GetAcitivites()** didn't returned all the activities it should.

Searching the forums I found a post from **Steve Garman** stating this:
_"Unfortunately this is caused by changes to package visibility rules introduced in apps targeting Android 11 and above
https://developer.android.com/training/package-visibility
There is no workaround for this as far as I know in the latest version of DroidScript"_

Followed by **Dave**'s message:
_"Showing all apps will be possible in the next 'X' release."_

src: https://groups.google.com/g/droidscriptpremium/c/pmqF0RHC83c

I think **app.GetInstalledApps()** and **app.GetAcitivites()** (maybe also **app.GetRunningApps()** and **app.GetRunningServices()**) should then be deprecated in DroidScript standard, with a warning notice explaining their possible limitations.

**Comment by alex-Symbroson** [comment]
I will mark them as X-Version only

**Comment by alex-Symbroson** [comment]
fixed by 32b649cc3a0b9e9ef6d0ec89da948890a5f13376
