### ISSUE TITLE
Typo: OnResume called OnPause in AppEvents

### ISSUE THREAD

**Issue by Right2TheV0id** [DroidScript/Docs#52]
In Intro/AppEvents there is a typo in the OnResume function description:
_"The **OnPause** event will be called when the user returns to your app after sending it to the background."_

It should be:
_"The **OnResume** event will be called when the user returns to your app after sending it to the background."_

**Comment by alex-Symbroson** [comment]
fixed by 32b649cc3a0b9e9ef6d0ec89da948890a5f13376
