### ISSUE TITLE
Full description not showing when running `node generate.js -c <scope>.<pattern>`

### ISSUE THREAD

**Issue by hamacjumar** [DroidScript/Docs#63]
If the full description is located in the `desc` folder which is reference through `"desc": "#Member.md"`, the description of the rendered html is just `#Member.md` instead of showing the content of `Member.md` in the desc folder. This issue occurs when generating a certain member of the scope. e.g. `node generate.js -c app.CreateButton`

**Comment by alex-Symbroson** [comment]
Fixed by #adf5f57
