### ISSUE TITLE
Automated In-App Docs updating, Git-Sourced Plugin Docs

### ISSUE THREAD

**Issue by alex-Symbroson** [DroidScript/Docs#92]
david enjineio Fri, 10 Feb, 14:34 to Jumar, me

I'd like to convert most of the DS functionality to run as a big bunch of plugins which carry their own documentation.  Currently the docs are all in one block, but I would like to break them up into separate plugins and make them open source so that others can contribute to them.

d_a_v_e — 13/02/2023 15:22
We'll probably have to keep the core framework docs as a single plugin, then Music, MUI, GameView, UI etc would all be updateable plugins (from the plugins menu)

Our new way of writing docs is to include comments in the javascript source code, then generate the docs from that, so we might have to create a set of dummy javascript files to represent the core functionality... possibly by hacking Symbroson's docs generator 
Any new functionality would be written as a DS plugin with documentation included.

We could put those plugins into our public git repo and others could contribute as and when they spot missing bits or mistakes
We can then update the docs for each part of DS without waiting for an official DS release
The administrator(s) of the git repo would moderate any pull requests for changes to the docs (or plugin code) 

I'm also thinking of moving all our plugins to git and changing the plugins list to point at that instead.... and allowing 3rd party plugins to be searched for and installed directly from git. 

Docs Tasks:
- [x] Integrate Docs update button directly in DS, use app.Execute to run within DS
- [x] ~~check Docs update compatibility with WEB IDE~~

**Comment by alex-Symbroson** [comment]
It would be thinkable to allow either [vscode-droidscript-docs](https://github.com/hamacjumar/vscode-droidscript-docs) or [vscode-droidscript-code](https://github.com/hamacjumar/vscode-droidscript-code) to somehow transfer the latest generated docs into DS

Also it is thinkable to write a DS extension that (semi-)automatically fetches and updates the latest docs from the repo, similar to, and to replace the [DocsPreview](https://ds.justplayer.de/uploads/docspreview). Probably need to compare the DS version?

**Comment by alex-Symbroson** [comment]
Suggestion: integrate update button directly in DS, use app.Execute to run within DS\
check Docs update compatibility with WEB IDE

**Comment by hamacjumar** [comment]
> Suggestion: integrate update button directly in DS, use app.Execute to run within DS check Docs update compatibility with WEB IDE

I'm for this recommendation.

**Comment by alex-Symbroson** [comment]
closed by 36fe8cc94e7562278b9762d237b2daa4c6aed074
